TheConnMan/jukebot

README.md
assets/js/app.js
views/homepage.ejs
views/layout.ejs

some small tweaks to the layout and some error checking

---

api/services/SyncService.js

see if there's a problem. this is likely the culprit code

add a catch statement here

---

api/services/YouTubeService.js

Adds the ability to match shortened video links

Fixes #25 - Accept Shortened YouTube Links

---

README.md
api/services/SyncService.js
config/env/development.js

Slack Notification Toggles

---

assets/js/app.js
views/layout.ejs

Add desktop notifications for new songs and now playing

---

api/controllers/ApiController.js
assets/js/app.js
assets/styles/jukebot.css
views/homepage.ejs
views/layout.ejs

Username Syncing

---

assets/js/app.js
assets/styles/jukebot.css
views/homepage.ejs
views/layout.ejs

added search functionality

---

assets/styles/jukebot.css
views/homepage.ejs

Combine Upcoming and Recent Videos

---

assets/js/app.js
assets/js/video.js
views/layout.ejs
views/partials/videos.ejs

@TheConnMan please pull down and test a bit. lots of refactoring. Hope you enjoy it!

Add from favorites

---

assets/js/app.js
assets/js/storage.js
assets/js/video.js
views/homepage.ejs
views/partials/favorites.ejs
views/partials/header.ejs
views/partials/videos.ejs

Favorites Menu

---

api/controllers/ApiController.js
api/controllers/ChatController.js
api/services/ChatService.js
api/services/SyncService.js
assets/components/chat.html
assets/js/components/chat.js
assets/styles/jukebot.css

Video Chats

---

assets/js/app.js
assets/js/video.js
views/layout.ejs
views/partials/videos.ejs

Thoughts on how it looks?
Closes #52

Video Duration

---

assets/components/chat.html
assets/js/components/chat.js
assets/styles/jukebot.css
views/homepage.ejs
views/partials/header.ejs
views/partials/videos.ejs

Allowing the chat notifications be a separate control vs video notifications.

allow the user to toggle video notifications vs chat notifications

---

README.md

I suggest using the more accurate "jukebot" instead of "jukebox"

Everything is called jukebox

---

api/controllers/ApiController.js

Only send machine notifications if a user leaves and does not come back within 1 second.

User refresh debounce

---

api/controllers/ChatController.js
assets/components/chat.html
assets/js/components/chat.js

Typing Indicator

---

CONTRIBUTING.md

Fixes TheConnMan/jukebot#104 - Create CONTRIBUTING.md

---

assets/styles/jukebot.css

floating notifications off to the right for clarity

---

api/controllers/ChatController.js
api/models/Chat.js
api/services/ChatService.js

closes #67 
I know you assigned yourself to this but I was just about to start working on Rooms but realized in order to do it properly, I should have a one-to-many relationship with Chats and Videos so Chats being modeled had to come first.

making chats as domain objects

---

assets/styles/jukebot.css
views/partials/header.ejs

making search stand out more

---

assets/components/chat.html
assets/js/components/chat.js

JukeBot Chats

---

api/controllers/ApiController.js
api/services/ChatService.js
api/services/SyncService.js
assets/js/components/chat.js
assets/js/components/playlist.js
assets/js/video.js

Additional Machine Messages

---

assets/js/app.js

adding icons to search results

---

README.md

Adds a link to Google Analytics for convenience.

Fixes TheConnMan/jukebot:113 - Google Analytics doc

---

.gitignore
README.md
api/services/SyncService.js
assets/js/video.js
config/bootstrap.js
config/connections.js
config/models.js
docker-compose.yml

Basic Data Persistence

---

api/controllers/ApiController.js
api/services/SyncService.js
api/services/YouTubeService.js
assets/js/app.js
assets/js/video.js

Friggen promises everywhere.
Closes #61

Playlist Support

---

views/partials/header.ejs

link to github issues page

---

api/services/YouTubeService.js
assets/components/playlist.html

Check for video thumbnails object before using it

---

api/controllers/ApiController.js
api/services/ChatService.js
api/services/SyncService.js
assets/components/chat.html
assets/js/components/chat.js

When adding the heart icons to chat I thought it might be cool to add additional icons to distinguish types of machine chat.

Chat Icons

---

api/controllers/ApiController.js
api/models/Video.js
api/services/SyncService.js
api/services/YouTubeService.js
assets/components/playlist-item.html
assets/components/playlist.html
assets/js/components/playlist-item.js
assets/js/components/playlist.js
assets/styles/jukebot.css
views/layout.ejs

Related videos

---

api/services/SyncService.js
config/bootstrap.js

Restart video if it should be playing after restart, skip otherwise

---

api/models/Chat.js
assets/components/chat.html
assets/components/heart.html
assets/components/playlist.html
assets/js/components/chat.js
assets/js/components/heart.js
assets/js/video.js
views/layout.ejs

Favoriting From Chat

---

assets/js/app.js
assets/js/components/playlist.js

Video Notifications

---

api/services/YouTubeService.js

Prevent autoplay from replaying recent videos

---

README.md
api/controllers/ApiController.js
api/services/ChatService.js
assets/js/components/chat.js
assets/js/video.js
config/globals.js
views/layout.ejs

Add environment variables for video and chat lifetimes

---

assets/components/playlist-item.html

show duration for related videos

---

assets/components/playlist.html

using anchor tags for pointer cursor

---

api/controllers/ApiController.js
api/services/SyncService.js
api/services/YouTubeService.js

Add videos from a playlist in order

---

assets/components/playlist.html
assets/js/components/playlist-item.js
assets/js/components/playlist.js

Remove autoscrolling when readding a video

---

assets/js/components/playlist.js

Scroll to the currently playing song on page load

---

api/controllers/ApiController.js
assets/components/chat.html
assets/js/components/playlist-item.js
assets/js/video.js

Add a machine message when a user removes a video from the playlist

---

README.md
api/controllers/ApiController.js
api/services/SyncService.js
config/globals.js

Add autodisable autoplay config

---

views/partials/header.ejs

max character length of 24

---

Dockerfile
README.md
config/connections.js
config/migrations.js
config/models.js
migrations/20170501223203-initial-schema.js
package.json
tasks/register/dbMigrate.js

Add an initial DB migration in preparation for optional user auth and persisted user settings.

DB Migrations

---

api/controllers/FavoriteController.js
api/models/Favorite.js
assets/js/app.js
assets/js/components/heart.js
assets/js/components/playlist-item.js
assets/js/favorites.js
assets/js/storage.js
config/policies.js
migrations/20170514005652-favorites.js
views/layout.ejs
views/partials/favorites.ejs

Sync Favorites

---

README.md

My goal is to bring the quick-start docs to the top and move the advanced docs to the bottom.

Doc Updates

---

api/services/SyncService.js
api/services/YouTubeService.js

Persist videos in the SyncService and send websocket updates immediately

---

api/models/Video.js
api/services/SyncService.js
migrations/20170602223431-video-autoplay-flag.js

Track autoplayed videos
